### PR TITLE
Display arrow for multiple select

### PR DESCRIPTION
**Pull request by wrmk**
the main changes were made in `src/scss/selectize.scss`
other came from `npm run build`

on line 333 `.#{$selectize}-control.single .#{$selectize}-input {` and `.single` did not allow to apply styles for multiple select
wrapped to apply styles for arrow for all selects

### CODE REVIEW

**Comment by wrmk** [comment]
old
image

new
image

**Comment by ksnitsky** [comment]
It was never previously displayed for multi select?

**Comment by wrmk** [comment]
it displayed our custom icon, but became broken when we migrate to tabler icons

**Comment by wrmk** [comment]
hub
image

**Review by ksnitsky — APPROVED** [review]

**Pull request merged**
